version: '3'

services:
  one_provider_gui:
    image: dockerhub.hi.inet/evolved-5g/capif/one_provider_gui:latest
    networks:
      - demo-network
    hostname: exposer
    container_name: one_provider_gui
    build:
      context: ./one_provider_gui
    volumes:
      - ./one_provider_gui:/usr/src/app
    environment:
      - CAPIF_HOSTNAME=${CAPIF_HOSTNAME}
      - REGISTER_HOSTNAME = register
      - EASY_RSA_HOSTNAME = easy-rsa
      - CAPIF_PORT=8080
      - EASY_RSA_PORT=8083
      - REGISTER_PORT=8084
    extra_hosts:
      - host.docker.internal:host-gateway
      - capifcore:host-gateway
      - register:host-gateway
      - easy-rsa:host-gateway

networks:
  demo-network:
    external: true

