apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "capif-provider-one.fullname" . }}-provider
  labels:
    io.kompose.service: capif-provider-one
  {{- include "capif-provider-one.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.28.0 (c4137012e)
spec:
  replicas: {{ .Values.oneProviderGui.replicas }}
  selector:
    matchLabels:
      io.kompose.service: capif-provider-one
    {{- include "capif-provider-one.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        io.kompose.service: capif-provider-one
      {{- include "capif-provider-one.selectorLabels" . | nindent 8 }}
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.28.0 (c4137012e)
    spec:
      imagePullSecrets:
        - name: regcred
      {{- if eq .Values.environment "kubernetes-athens" }}
      hostAliases:
        - ip: "{{ .Values.ingress_ip.athens }}"
          hostnames:
            - "{{ .Values.oneProviderGui.oneProviderGui.env.capifHostname }}"
      {{- end }}
      {{- if eq .Values.environment "kubernetes-uma" }}
      hostAliases:
        - ip: "{{ .Values.ingress_ip.uma }}"
          hostnames:
            - "{{ .Values.oneProviderGui.oneProviderGui.env.capifHostname }}"
      {{- end }}
      containers:
      - env:
        - name: CAPIF_HOSTNAME
          value: {{ quote .Values.oneProviderGui.oneProviderGui.env.capifHostname }}
        - name: CAPIF_PORT
          value: {{ quote .Values.oneProviderGui.oneProviderGui.env.capifPort }}
        - name: EASY_RSA_PORT
          value: {{ quote .Values.oneProviderGui.oneProviderGui.env.easyRsaPort }}
        - name: REQUESTS_CA_BUNDLE
          value: {{ quote .Values.oneProviderGui.oneProviderGui.env.requestsCaBundle }}
        - name: SSL_CERT_FILE
          value: {{ quote .Values.oneProviderGui.oneProviderGui.env.sslCertFile }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.oneProviderGui.oneProviderGui.image.repository }}-{{ .Values.oneProviderGui.oneProviderGui.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: Always
        name: one-provider-gui
        ports:
        - containerPort: 8085
        resources: {}
      restartPolicy: Always