apiVersion: v1
kind: Service
metadata:
  name: capif-provider-one
  labels:
    io.kompose.service: capif-provider-one
  {{- include "capif-provider-one.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.28.0 (c4137012e)
spec:
  type: {{ .Values.oneProviderGui.type }}
  selector:
    io.kompose.service: capif-provider-one
  {{- include "capif-provider-one.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.oneProviderGui.ports | toYaml | nindent 2 -}}